include:
  - project: 'drupalspoons/webmasters'
    # Best practice is to pin to a tag or a SHA1. https://docs.gitlab.com/ee/ci/yaml/#includefile
    ref: 1.4.1
    file: 'templates/.gitlab-ci.yml'

# Projects can override anything in the included template. See https://docs.gitlab.com/ee/ci/yaml/README.html#include
# Comment out the code below if you are copying this file to your project.
# Add /webprofiler to ignored paths.
code_style:
  script:
    - PWD=$(pwd) && vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --runtime-set ignore_errors_on_exit 1 --ignore=$PWD/web/,$PWD/vendor/,$PWD/webprofiler/ --report-junit=junit.xml --report-full --report-summary

